name: Simple Test Workflow-1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello, GitHub Actions is working!"

      - name: Show files
        run: ls -l
